### PR TITLE
Add SalemoveSDK in podspec

### PR DESCRIPTION
**Pull request by gersonnoboa**
In order to release GliaWidgets for Cocoapods, we need to add SalemoveSDK as a podspec. Otherwise, when the integrator wants to use `GliaWidgets` in their podfile, Cocoapods will complain that it doesn't know where to get SalemoveSDK from. I copied and pasted the spec that we have in ios-bundle, as using that one made me integrate Cocoapods successfully in my internal tests.

### CODE REVIEW

**Review by dukhovnyi — APPROVED** [review]
Looks good. Only one thing about 0.29.5, I don't know do we need to update this PR to 0.29.5 (and remove part of dependencies) or not. What do you think?

**Comment by gersonnoboa** [comment]
@dukhovnyi It can be, yes. I will test this tomorrow.

**Review by gugalo — APPROVED** [review]

**Comment by gersonnoboa** [comment]
@dukhovnyi I have updated and tested with the new 0.29.6 version, you can see it here, https://github.com/salemove/glia-ios-podspecs/blob/7b29f5540642917fdb2b3808a12972d1a42713c5/SalemoveSDK/0.29.6/SalemoveSDK.podspec. The unnecessary dependencies were removed and the version has been replaced with 0.29.6.

**Comment by gersonnoboa** [comment]
!merge

**Pull request merged**
